---
version: "2.1"
services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - .env
    volumes:
      - ./config:/config
    network_mode: host
    restart: unless-stopped